GET http://localhost:3000/api/rentals?order=desc HTTP/1.1

###

POST http://localhost:3000/api/rentals HTTP/1.1
Content-Type: application/json

{
  "personaId": 5000,
  "numUnits": 4
}

###

GET http://localhost:3000/api/rentals/1 HTTP/1.1

###

POST http://localhost:3000/api/rentals HTTP/1.1

{
  ""
}

###

GET https://api.zeus.projects.bbdgrad.com/start-time HTTP/1.1